server:
  port: 8090

spring:
  application:
    name: msvc-student
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_student
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://${CONFIG_SERVER:localhost}:8888


eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka