server:
  port: 9090
spring:
  application:
    name: msvc-course
  config:
    import: optional:configserver:http://${CONFIG_SERVER:localhost}:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/db_course
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka