server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka/


